#cloud-config

apt:
  primary:
    - arches: [default]
      uri: https://mirrors.ustc.edu.cn/ubuntu
  sources:
    docker.list:
      source: deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes.list:
      source: deb https://mirrors.ustc.edu.cn/kubernetes/apt/ kubernetes-xenial main
      keyid: 7F92E05B31093BEF5A3C2D38FEEA9169307EA071


write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/security/limits.conf
    content: |
      *		soft		nofile	655350
      *		hard		nofile	655350
      *		soft		nproc	655350
      *		hard		nproc	655350
      root		soft		nofile	655350
      root		hard		nofile	655350
      root		soft		nproc	655350
      root		hard		nproc	655350
  - path: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  - path: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  - path:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

users:
  - name: root
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCh1W0lkrrU6DAWVNcb/hUCp/JRi1OOSSMhyvJX1Bz0d5VWQ1D9KxSm1tGT8zxsHjmt86LYiPmHLzbfnKmoWb2xaXd7EwM+w8XRwXVZYgd0I6YFEiz9KXHQCwHdSTkDF3mmqaIOP4mmxITbaqzOPgwG6ZimTpZe/qm/ILmtRb75VeEz7UPQ/qvCFKw+OvrMpBBpaoVjPGQKf61wFiBMPVtSvmN76SegWhuENlyWVPd5Cs54zaSEesIq3u2kXHmaWAsTXVCf40ZqXMfxyYRqr+VYXC43O2nrNMYYyZqVEU+ltRNIBW8nUveoKuHTEbIk3I0ePqm8Cfyq3iaoHwxaQMOl zsnmwy@github/55856557 # ssh-import-id gh:zsnmwy

timezone: Asia/Shanghai
disable_root: false

packages:
  - socat
  - conntrack
  - ebtables
  - ipset
  - zsh
  - chrony
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - aptitude
  - jq
  - containerd.io
  - kubelet
  - kubeadm
  - kubectl
